export enum MySqlCode {
  DUPLICATED_ENTRY = 'ER_DUP_ENTRY', // 1062
  FK_INSERT_OR_UPDATE = 'ER_NO_REFERENCED_ROW_2', // 1452
  FK_DELETE_OR_UPDATE = 'ER_ROW_IS_REFERENCED_2', // 1451
  NOT_NULL = 'ER_BAD_NULL_ERROR', // 1048
  CHECK_FAILED = 'ER_CHECK_CONSTRAINT_VIOLATED', // 3819
  DATA_TOO_LONG = 'ER_DATA_TOO_LONG', // 1406
  TRUNCATED_WRONG_VALUE = 'ER_TRUNCATED_WRONG_VALUE', // 1366
  INVALID_DEFAULT = 'ER_INVALID_DEFAULT', // 1067
}