export const EMAIL_ALLOWED_STYLE_NAMES = [
  'background-color',
  'border',
  'border-radius',
  'border-spacing',
  'border-style',
  'color',
  'display',
  'font-family',
  'font-size',
  'font-weight',
  'height',
  'line-height',
  'margin',
  'max-height',
  'max-width',
  'min-height',
  'min-width',
  'opacity',
  'overflow',
  'padding',
  'table-layout',
  'text-align',
  'text-decoration',
  'width',
  'word-break',
  'word-wrap',
] as const
