resolver 127.0.0.11 valid=30s;

upstream api {
  zone api 64k;
  server api:3000 resolve;
}

server {
  listen 80;
  server_name spaces;

  access_log off;

  root /var/www/spaces;
  index index.html index.htm;
  error_page 404 /404.html;

  location / {
    try_files $uri $uri/ /index.html;

    location /backend/ {
      proxy_pass http://api/;
      proxy_set_header X-Forwarded-Proto https;
    }
  }
}

server {
  listen 80;
  server_name quiz;

  access_log off;

  root /var/www/quiz;
  index index.html index.htm;
  error_page 404 /404.html;

  location / {
    try_files $uri $uri/ /index.html;

    location /backend/ {
      proxy_pass http://api/;
      proxy_set_header X-Forwarded-Proto https;
    }
  }
}
