export const SPACE_NAME_MAX_LENGTH = 150;
export const QUIZ_NAME_MAX_LENGTH = 150;
export const QUESTION_NAME_MAX_LENGTH = 100;

export const SENDER_NAME_MAX_LENGTH = 80;
export const SENDER_EMAIL_MAX_LENGTH = 150;
export const SENDER_PHONE_MAX_LENGTH = 25;
export const EMAIL_SUBJECT_MAX_LENGTH = 150;
export const EMAIL_CONTENT_MAX_LENGTH = 10000;
export const MESSAGE_CONTENT_MAX_LENGTH = 2000;

export const LEARNER_NAME_MAX_LENGTH = 80;
export const LEARNER_EMAIL_MAX_LENGTH = 150;

export const ACCOUNT_SETTINGS_EMAIL_MAX_LENGTH = 150;
export const ACCOUNT_SETTINGS_PASSWORD_MAX_LENGTH = 80;
