version: "3"
services:
  garage:
    image: dxflrs/garage:v1.1.0
    container_name: "garage_image_server"
    network_mode: "host"
    restart: unless-stopped
    ports:
      - 3900:3900 
      - 3901:3901
      - 3902:3902
      - 3903:3903
    volumes:
      - ./garage.toml:/etc/garage.toml
      - ./meta:/var/lib/garage/meta
      - ./data:/var/lib/garage/data
    environment:
      - RUST_LOG=garage=debug