version: "3"
services:
  images:
    image: "dxflrs/garage:v2.3.0"
    ports:
      - 3900:3900 
      - 3901:3901
      - 3902:3902
      - 3903:3903
    restart: "unless-stopped"
    volumes:
    - "images-data:/var/lib/garage/"
    - "./garage.toml:/etc/garage.toml"
    healthcheck:
      test:
      - "CMD"
      - "/garage"
      - "status"
      interval: "30s"
      timeout: "10s"
      retries: 10
      start_period: "10s"
volumes:
  images-data: