version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    expose:
      - '3306'
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - shira-network
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
    networks:
      - shira-network
    expose:
      - '6379'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis-data:/data

networks:
  shira-network:
    external: true

volumes:
  db-data:
  redis-data:
