version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"    
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - nestjs-network
  redis:
    image: 'bitnami/redis:latest'
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    networks:
      - nestjs-network
    expose:
      - '6379'
    volumes: 
      - redis-data:/data
  

networks:
  nestjs-network:

volumes:
  db-data:
  redis-data: